version: '3.8'

networks:
  server_network:
    external: true

services:
  # --- [Cloudflare Tunnel] ---
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    networks:
      - server_network

  # --- [Authentik DB & Cache] ---
  postgresql:
    image: docker.io/library/postgres:12-alpine
    container_name: auth-postgres
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=authentik
      - POSTGRES_DB=authentik
    networks:
      - server_network

  redis:
    image: docker.io/library/redis:alpine
    container_name: auth-redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - server_network

  # --- [Authentik Core] ---
  authentik-server:
    image: ghcr.io/goauthentik/server:2023.10.0
    container_name: authentik-server
    restart: unless-stopped
    command: server
    environment:
      - AUTHENTIK_REDIS__HOST=auth-redis
      - AUTHENTIK_POSTGRESQL__HOST=auth-postgres
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_PASS}
      - AUTHENTIK_SECRET_KEY=${AUTH_SECRET}
    ports:
      - "9000:9000"
      - "9443:9443"
    depends_on:
      - postgresql
      - redis
    networks:
      - server_network

  authentik-worker:
    image: ghcr.io/goauthentik/server:2023.10.0
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    environment:
      - AUTHENTIK_REDIS__HOST=auth-redis
      - AUTHENTIK_POSTGRESQL__HOST=auth-postgres
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_PASS}
      - AUTHENTIK_SECRET_KEY=${AUTH_SECRET}
    depends_on:
      - postgresql
      - redis
    networks:
      - server_network

volumes:
  db_data: